Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.box_check_update = false
    config.vm.hostname = "JD"
    config.vm.synced_folder ".", "/vagrant", type: "rsync"
    config.vm.network "forwarded_port", guest: 8080, host: 8080 # Jenkins

    # Provisioning with ansible
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yaml"
    end

    # Machine specs
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "8096"
      vb.cpus = "2"
    end

    # cache the packages
    if Vagrant.has_plugin?("vagrant-cachier")
      config.cache.scope = :box
    end

end