- name: Add an apt signing key for Jenkins
  apt_key:
    url: "{{ jenkins_signing_key_url }}"
    state: present

- name: Add Jenkins apt repo
  apt_repository:
    repo: "{{ jenkins_apt_repo }}"
    state: present
    filename: jenkins
    update_cache: yes


- name: Install JRE 
  apt:
    name: openjdk-8-jre
    state: present 

- name: Install Jenkins 
  apt:
    name: jenkins
    state: present 

- getent:
    database: group
    split: ':'

- name: Add jenkins to docker group (only if docker group already exists)
  user: 
      name: jenkins
      group: docker
  when: item in ansible_facts.getent_group
  with_items: 
    - docker


- name: Disable jenkins setup wizard
  lineinfile:
    path: "{{ jenkins_config_file }}"
    line: JAVA_ARGS="-Djenkins.install.runSetupWizard=false"

- name: Create groovy init directory 
  file:
    path: "{{ groovy_init_dir }}"
    state: directory
    mode: '0777'

- name: Place basic security script in groovy directory
  get_url:
    url: "{{ groovy_basic_security_url }}"
    dest: "{{ groovy_init_dir }}/basic-security.groovy"
    mode: '0777'

- name: Enable and start jenkins service 
  service:
    name: jenkins 
    enabled: yes 
    state: started

- name: Include wait for jenkins task
  include_tasks: jenkins_check.yml

- name: Download Plugins script into vagrant home directory
  get_url:
    url: "{{ plugins_script_url }}"
    dest: "{{ vagrant_home_dir }}"
    mode: '0777'

- name: Restart jenkins service 
  service:
      name: jenkins
      state: restarted

- name: Include wait for jenkins task
  include_tasks: jenkins_check.yml

- name: Download jenkins cli into vagrant home directory 
  get_url:
    url: "{{ jenkins_cli_url }}"
    dest: "{{ vagrant_home_dir }}"
    mode: '0777'
  retries: 5
  delay: 5
  register: result      
  until: result is succeeded

- name: Run plugins scripts
  shell: "{{vagrant_home_dir}}/plugins.sh"
  args:
    executable: /bin/bash
  register: plugins_script

- name: Show installed plugins
  debug:
    var: plugins_script.stdout

- name: Restart jenkins service 
  service:
      name: jenkins
      state: restarted